repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3
-   repo: https://github.com/prettier/prettier
    rev: "1.12.1"
    hooks:
    - id: prettier
