version: 2.1
jobs:
  cypress:
    machine:
      image: ubuntu-1604:202004-01
    working_directory: ~/inspirehep
    steps:
      - checkout
      - run:
          name: Install Node
          command: |
            set +e

            echo 'export NVM_DIR="/opt/circleci/.nvm"' >> $BASH_ENV
            echo ' [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> $BASH_ENV
            
            export NVM_DIR="/opt/circleci/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            
            nvm install v10.14.0
            nvm alias default 10.14.0
    
            rm -rf ~./node-gyp
      - run:
          name: Install Yarn
          command: npm install -g yarn@1.22.4
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-package-cache-{{ checksum "ui/yarn.lock" }}-{{ checksum "record-editor/yarn.lock" }}
      - run:
          name: Setup and Run Tests
          command: sh cypress-tests.sh
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-package-cache-{{ checksum "ui/yarn.lock" }}-{{ checksum "record-editor/yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - store_artifacts:
          path: e2e/cypress/__screenshots__
      - store_artifacts:
          path: e2e/cypress/__snapshots__
      - store_artifacts:
          path: cypress-containers.log
workflows:
  version: 2
  e2e:
    jobs:
      - cypress
