version: 2.1
jobs:
  cypress:
    machine:
      image: ubuntu-1604:202004-01
    working_directory: ~/inspirehep
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-cache-{{ checksum "ui/yarn.lock" }}-{{ checksum "record-editor/yarn.lock" }}
      - run: sh cypress-tests.sh
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-cache-{{ checksum "ui/yarn.lock" }}-{{ checksum "record-editor/yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - store_artifacts:
          path: e2e/cypress/__screenshots__
      - store_artifacts:
          path: e2e/cypress/__snapshots__
      - store_artifacts:
          path: cypress-container-logs.txt
workflows:
  version: 2
  e2e:
    jobs:
      - cypress
