version: 2.1
jobs:
  cypress:
    machine:
      image: ubuntu-1604:202004-01
    working_directory: ~/inspirehep
    steps:
      - checkout
      - run: sh cypress-tests.sh
      - store_artifacts:
          path: smoke-tests/cypress/__screenshots__
      - store_artifacts:
          path: smoke-tests/cypress/__snapshots__
      - store_artifacts:
          path: cypress-container-logs.txt
workflows:
  version: 2
  e2e:
    jobs:
      - cypress
